---
- name: "Install nmapAutomator"
  block:
  - name: "Clone nmapAutomator"
    git:
      repo: "https://github.com/21y4d/nmapAutomator"
      dest: "/opt/nmapAutomator"
  - name: "Install nmapAutomator dependencies"
    apt:
      name:
        - ffuf
        - gobuster
      state: present
      update_cache: no
  - name: "Create symbolic link to nmapAutomator.sh in /usr/local/bin"
    shell: ln -sf /opt/nmapAutomator/nmapAutomator.sh /usr/local/bin/
  
  become: true
  become_method: sudo

