---
- name: "Install tmux"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copy tmux configuration file"
  copy:
    src: "{{ playbook_dir }}/roles/configure-tmux/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/"
- name: "Install tmux plugins"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    clone: yes
    update: yes

